import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Navbar from "@/components/nav/navbar";
import Card from "@/components/card/card";
import SectionCards from "@/components/card/section-cards";
import getVideos, { getPopularVideos } from "@/lib/videos";
const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  // const disneyVideos = await getCommonVideos("disney videos");
  // const productivityVideos = await getCommonVideos("productivity videos");
  // const travelVideos = await getCommonVideos("travel videos");
  const popularVideos = await getPopularVideos();
  const getVideos = await getPopularVideos();
  return {
    props: { getVideos, popularVideos },
  };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  popularVideos,
  getVideos,
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar username={"ankita"} />
        <Banner
          title={"Clifford the red dog"}
          subTitle={"string"}
          imgUrl={"/static/clifford.webp"}
        />
        <div className={styles.sectionWrapper}></div>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Travel" videos={getVideos} size="small" />
        <SectionCards
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        />
        <SectionCards title="Popular" videos={popularVideos} size="small" />
      </main>
    </>
  );
}
